### ISSUE TITLE
Stub out Ship Class

### ISSUE THREAD

**Issue by gkonczol** [ctsstc/galaga-invaders-alpha-7#1]
We need a basic ship class with basic members.

## Basic Members
- x
- y
- height
- width
- sprite

**Comment by ctsstc** [comment]
This looks to meet the criteria 👍  :shipit: LGTM!
Closed with merge https://github.com/ctsstc/galaga-invaders-alpha-7/commit/f797bf49262031b0af893d547b1b7812d7f0a746
